### ISSUE TITLE
Choose three suitable themes for qswp.com project

### ISSUE THREAD

**Issue by itprokcmo** [databasically/qswp2015#1]
-clean and professional
-fresh
-corporate feel

**Comment by itprokcmo** [comment]
How about these Wes?  I searched "corporate" via wrapbootstrap.com and found these.  I think that there is potential in these templates once we add Terry's site logo in place of logos displayed and then maybe a hd quality picture of Terry posing like Steve Jobs smiling, that could go in the placeholder of one of the images in the templates below that scales a larger area of the screen.  Thoughts?

![boottemp1](https://cloud.githubusercontent.com/assets/5615132/7823923/adfc2eaa-03c4-11e5-8d7b-a344b4ff33c4.PNG)
https://wrapbootstrap.com/theme/origami-responsive-multipurpose-theme-WB0P92B70

![boottemp2](https://cloud.githubusercontent.com/assets/5615132/7823944/caf21506-03c4-11e5-8000-d2e0c4b4fc61.PNG)
https://wrapbootstrap.com/theme/lumia-clean-complete-business-theme-WB02H2J66

![boottemp3](https://cloud.githubusercontent.com/assets/5615132/7823960/dadc5cce-03c4-11e5-8325-c84e967e6076.PNG)
https://wrapbootstrap.com/theme/deedee-5-color-responsive-theme-WB04P3053

**Comment by wesgarrison** [comment]
>  then maybe a hd quality picture of Terry posing like Steve Jobs smiling

ha! probably not.

> deedee-5-color-responsive-theme-WB04P3053

My favorite so far.

> Lumia

not a fan, the video callout isn't helpful

**Comment by itprokcmo** [comment]
approved final template by Wes, to replace the lumia template in first pitch idea:
![template2](https://cloud.githubusercontent.com/assets/5615132/7845723/50412bac-047e-11e5-862b-35303dd37798.png)

**Comment by centdev13** [comment]
To be clear I meant final template as the final template in the three that will be pitched to Terry.

**Comment by itprokcmo** [comment]
You had stated that you want me to get started on the project and then we can drop in the bootstrap template, but I'm not sure how to do that.  Is there any way we can set up a team-viewer session remotely sometime asap?

**Comment by wesgarrison** [comment]
Maybe start with the basic bootstrap template.

And sure, we can do a call.  Ping me tomorrow in Slack and we can set something up.  3 PM?

**Comment by itprokcmo** [comment]
Yeah, that works.  3PM.

**Comment by itprokcmo** [comment]
Wes bought the "DeeDee" template for me to learn with and try and tie the concepts together for this project.  No final template decided on yet though.
